### ISSUE TITLE
Course Files

### ISSUE THREAD

**Issue by LondonWebFactory** [JeffreyWay/Laravel-From-Scratch-Blog-Project#1]
Hi Jeffrey

I would be happy to pay for your Laravel 8 course but I don't see any incremental source code files. I believe that in the past you offered a source code download link with each lesson.  

Kind Regards,
Adrian

**Comment by JeffreyWay** [comment]
If a lesson has available source code, you'll find it here: https://github.com/JeffreyWay/Laravel-From-Scratch-Blog-Project/commits/main

**Comment by Sakthi002** [comment]
Please add Subtitles!!!!
