### ISSUE TITLE
Unwanted Question Mark @ Line 47 AppServiceProvider.php

### ISSUE THREAD

**Issue by th3hero** [JeffreyWay/Laravel-From-Scratch-Blog-Project#3]
return request()->user()?->can('admin');

**Comment by kunal254** [comment]
I think that is a [null safe operator](https://wiki.php.net/rfc/nullsafe_operator).

**Comment by th3hero** [comment]
I know but that's throwing an error while migrating to database, I don't know that happened just with or anyone else, but when I removed it, worked fine!.

**Comment by kunal254** [comment]
Hi, could you please attach the screenshot of the error here.

**Comment by th3hero** [comment]
![error](https://user-images.githubusercontent.com/82366975/148414314-ebea38d1-b62c-4878-b9f5-d0c85aebfedf.png)

Kindly have a look.

**Comment by kunal254** [comment]
well that's makes no sense to me. sorry bro.

**Comment by Shoovoon** [comment]
How did you solved the issue?

**Comment by lucasjose501** [comment]
That syntax requires PHP 8.0 or newer to work

**Comment by Shoovoon** [comment]
> That syntax requires PHP 8.0 or newer to work

-I changed my Php version to 8.0 from 7.4 from laragon, didnt work.
-Changed required php version ["php": "^7.3|^8.0",]  on composer.json file, didnt work.

Please guide me to tackle this kind of problem.

**Comment by lucasjose501** [comment]
As you are using Laragon, maybe your composer is reading your path variable that have php 7.4 defined and not your recent 8.0 version. Test it opening the cmd and type "php -v" to confirm.
Usually what works for me is opening Laragon and: "Menu > Tools > Path > Remove Laragon from Path" and then again but add it to the Path.
Try it and see if works
